apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-claim
  namespace: samba
  labels:
    app: samba
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
